name: Release

on:
  push:
    branches:
      - release

jobs:
  Call_Release_Workflow_in_doyto-oss-parent:
    uses: doytowin/doyto-oss-parent/.github/workflows/release.yml@main
    secrets: inherit
